# Generated by Django 5.1 on 2024-08-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='image',
            name='prompt',
            field=models.CharField(db_index=True, default='generic prompt', max_length=200),
        ),
    ]
