# Generated by Django 5.1 on 2024-08-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_generation', '0002_rename_name_image_file_name_image_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created',
        ),
        migrations.RemoveField(
            model_name='image',
            name='modified',
        ),
    ]
