# Generated by Django 5.1 on 2024-08-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generation', '0004_image_created_at_image_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
